import type { FieldDef } from "./types";

/** Shared endpoint / TLS / load / publish fields used by LLM, VLM, ASR. */
export function sharedEndpointFields(opts?: {
  requestTimeoutDefault?: number;
}): FieldDef[] {
  const requestTimeout = opts?.requestTimeoutDefault ?? 300;
  return [
    {
      key: "url",
      flag: "url",
      label: "URL",
      description:
        "Endpoint URL. Mutually exclusive with Endpoints file. Required with API key.",
      type: "url",
      group: "Endpoint",
      required: true,
      exclusiveWith: ["endpointsFile"],
      placeholder: "http://127.0.0.1:18321/v1/chat/completions",
    },
    {
      key: "apiKey",
      flag: "api-key",
      label: "API key",
      description: "Bearer token. Use any placeholder such as dummy when unused.",
      type: "password",
      group: "Endpoint",
      required: true,
      exclusiveWith: ["endpointsFile"],
      placeholder: "dummy",
    },
    {
      key: "endpointsFile",
      flag: "endpoints-file",
      label: "Endpoints file",
      description: "YAML endpoints file. Mutually exclusive with URL / API key.",
      type: "path",
      group: "Endpoint",
      exclusiveWith: ["url", "apiKey"],
      placeholder: "endpoints.yaml",
    },
    {
      key: "loadBalancer",
      flag: "load-balancer",
      label: "Load balancer",
      type: "select",
      group: "Endpoint",
      defaultValue: "round-robin",
      omitWhenDefault: true,
      options: [
        { value: "round-robin", label: "round-robin" },
        { value: "least-inflight", label: "least-inflight" },
      ],
    },
    {
      key: "insecure",
      flag: "insecure",
      label: "Insecure TLS",
      description: "Disable TLS certificate verification.",
      type: "boolean",
      group: "Endpoint",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "caCert",
      flag: "ca-cert",
      label: "CA cert",
      type: "path",
      group: "Endpoint",
      placeholder: "/path/to/ca.pem",
    },
    {
      key: "requestTimeout",
      flag: "request-timeout",
      label: "Request timeout (s)",
      type: "number",
      group: "Timeouts",
      defaultValue: requestTimeout,
      omitWhenDefault: true,
      min: 1,
    },
    {
      key: "connectTimeout",
      flag: "connect-timeout",
      label: "Connect timeout (s)",
      type: "number",
      group: "Timeouts",
      defaultValue: 30,
      omitWhenDefault: true,
      min: 1,
    },
    {
      key: "poolIdleTimeout",
      flag: "pool-idle-timeout",
      label: "Pool idle timeout (s)",
      type: "number",
      group: "Timeouts",
      defaultValue: 60,
      omitWhenDefault: true,
      min: 1,
    },
    {
      key: "tcpKeepalive",
      flag: "tcp-keepalive",
      label: "TCP keepalive (s)",
      type: "number",
      group: "Timeouts",
      defaultValue: 60,
      omitWhenDefault: true,
      min: 1,
    },
  ];
}

export function sharedLoadFields(opts?: {
  concurrencyDefault?: number;
  numRequestsRequired?: boolean;
}): FieldDef[] {
  return [
    {
      key: "numRequests",
      flag: "num-requests",
      label: "Num requests",
      type: "number",
      group: "Load",
      required: opts?.numRequestsRequired !== false,
      min: 1,
      defaultValue: 16,
      omitWhenDefault: false,
    },
    {
      key: "concurrency",
      flag: "concurrency",
      label: "Concurrency",
      type: "number",
      group: "Load",
      required: true,
      min: 1,
      defaultValue: opts?.concurrencyDefault ?? 4,
      omitWhenDefault: false,
    },
    {
      key: "warmupRequests",
      flag: "warmup-requests",
      label: "Warmup requests",
      type: "number",
      group: "Load",
      defaultValue: 0,
      omitWhenDefault: true,
      min: 0,
    },
    {
      key: "requestRate",
      flag: "request-rate",
      label: "Request rate (req/s)",
      description: "Open-loop rate. Omit for closed-loop concurrency.",
      type: "number",
      group: "Load",
      min: 0,
    },
    {
      key: "arrival",
      flag: "arrival",
      label: "Arrival",
      type: "select",
      group: "Load",
      defaultValue: "constant",
      omitWhenDefault: true,
      options: [
        { value: "constant", label: "constant" },
        { value: "poisson", label: "poisson" },
      ],
    },
    {
      key: "maxConcurrency",
      flag: "max-concurrency",
      label: "Max concurrency",
      description: "Hard cap for outstanding requests in open-loop mode.",
      type: "number",
      group: "Load",
      min: 1,
    },
    {
      key: "stopAfterSeconds",
      flag: "stop-after-seconds",
      label: "Stop after (s)",
      type: "number",
      group: "Load",
      min: 1,
    },
    {
      key: "rampUpSeconds",
      flag: "ramp-up-seconds",
      label: "Ramp up (s)",
      type: "number",
      group: "Load",
      min: 0,
    },
    {
      key: "seed",
      flag: "seed",
      label: "Seed",
      type: "number",
      group: "Load",
      defaultValue: 0,
      omitWhenDefault: true,
    },
    {
      key: "runs",
      flag: "runs",
      label: "Runs",
      description:
        "Sequential independent runs via unified entry point (before --).",
      type: "number",
      group: "Load",
      defaultValue: 1,
      omitWhenDefault: true,
      min: 1,
    },
  ];
}

export function sharedPublishFields(): FieldDef[] {
  return [
    {
      key: "sut",
      flag: "sut",
      label: "SUT file",
      description: "Operator-declared SUT JSON/YAML embedded in summary.",
      type: "path",
      group: "Publish / SUT",
      placeholder: "sut.json",
    },
    {
      key: "requireSut",
      flag: "require-sut",
      label: "Require SUT",
      type: "boolean",
      group: "Publish / SUT",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "redactHostname",
      flag: "redact-hostname",
      label: "Redact hostname",
      type: "boolean",
      group: "Publish / SUT",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "islTarget",
      flag: "isl-target",
      label: "ISL target",
      type: "number",
      group: "Publish / SUT",
      min: 0,
    },
    {
      key: "oslTarget",
      flag: "osl-target",
      label: "OSL target",
      type: "number",
      group: "Publish / SUT",
      min: 0,
    },
    {
      key: "islTolerance",
      flag: "isl-tolerance",
      label: "ISL tolerance",
      type: "number",
      group: "Publish / SUT",
      defaultValue: 0,
      omitWhenDefault: true,
      min: 0,
    },
    {
      key: "oslTolerance",
      flag: "osl-tolerance",
      label: "OSL tolerance",
      type: "number",
      group: "Publish / SUT",
      defaultValue: 0,
      omitWhenDefault: true,
      min: 0,
    },
    {
      key: "promptMixReport",
      flag: "prompt-mix-report",
      label: "Prompt mix report",
      type: "path",
      group: "Publish / SUT",
    },
    {
      key: "failOnOslMismatch",
      flag: "fail-on-osl-mismatch",
      label: "Fail on OSL mismatch",
      type: "boolean",
      group: "Publish / SUT",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "pricePerHour",
      flag: "price-per-hour",
      label: "Price per hour ($)",
      type: "number",
      group: "Publish / SUT",
      min: 0,
      step: 0.01,
    },
  ];
}

export function sharedAdvancedFields(opts?: {
  logLevelDefault?: string;
}): FieldDef[] {
  return [
    {
      key: "logLevel",
      flag: "log-level",
      label: "Log level",
      type: "select",
      group: "Advanced",
      defaultValue: opts?.logLevelDefault ?? "warn",
      omitWhenDefault: true,
      options: [
        { value: "error", label: "error" },
        { value: "warn", label: "warn" },
        { value: "info", label: "info" },
        { value: "debug", label: "debug" },
        { value: "trace", label: "trace" },
      ],
    },
    {
      key: "debugLog",
      flag: "debug-log",
      label: "Debug log",
      type: "path",
      group: "Advanced",
      defaultValue: "debug.log",
      omitWhenDefault: true,
    },
    {
      key: "errorLog",
      flag: "error-log",
      label: "Error log",
      type: "path",
      group: "Advanced",
      defaultValue: "error.log",
      omitWhenDefault: true,
    },
    {
      key: "slo",
      flag: "slo",
      label: "SLO thresholds",
      description: "Repeatable goodput thresholds.",
      type: "slo-list",
      group: "Advanced",
      defaultValue: [],
    },
    {
      key: "throughputBinSeconds",
      flag: "throughput-bin-seconds",
      label: "Throughput bin (s)",
      type: "number",
      group: "Advanced",
      defaultValue: 10,
      omitWhenDefault: true,
      min: 1,
    },
    {
      key: "extraBodyJson",
      flag: "extra-body-json",
      label: "Extra body JSON",
      type: "json",
      group: "Advanced",
      placeholder: '{"reasoning_effort":"medium"}',
    },
    {
      key: "systemPrompt",
      flag: "system-prompt",
      label: "System prompt",
      type: "textarea",
      group: "Advanced",
    },
    {
      key: "ignoreEos",
      flag: "ignore-eos",
      label: "Ignore EOS",
      type: "boolean",
      group: "Advanced",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "minTokens",
      flag: "min-tokens",
      label: "Min tokens",
      type: "number",
      group: "Advanced",
      min: 0,
    },
    {
      key: "uniquePrompts",
      flag: "unique-prompts",
      label: "Unique prompts",
      type: "boolean",
      group: "Advanced",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "tokenizer",
      flag: "tokenizer",
      label: "Tokenizer path",
      type: "path",
      group: "Advanced",
    },
    {
      key: "failOnError",
      flag: "fail-on-error",
      label: "Fail on error",
      type: "boolean",
      group: "Advanced",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "ntpCheck",
      flag: "ntp-check",
      label: "NTP check",
      type: "boolean",
      group: "Advanced",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "quiet",
      flag: "quiet",
      label: "Quiet",
      type: "boolean",
      group: "Advanced",
      booleanFlag: true,
      defaultValue: false,
    },
  ];
}
