import type { CommandDef } from "../types";
import {
  sharedAdvancedFields,
  sharedEndpointFields,
  sharedLoadFields,
  sharedPublishFields,
} from "../shared-fields";

export const asrCommand: CommandDef = {
  id: "asr",
  title: "ASR",
  description: "Audio transcription benchmark (latency, RTFx, optional WER/CER).",
  href: "/asr",
  binary: "metrum-ai-bench-cli",
  subcommand: ["asr"],
  useDoubleDash: true,
  supportsRuns: true,
  fields: [
    {
      key: "scenario",
      flag: "scenario",
      label: "Scenario",
      type: "string",
      group: "Workload",
      required: true,
      defaultValue: "asr",
      omitWhenDefault: false,
    },
    {
      key: "model",
      flag: "model",
      label: "Model",
      type: "string",
      group: "Workload",
      required: true,
      defaultValue: "dummy",
      omitWhenDefault: false,
    },
    {
      key: "input",
      flag: "input",
      label: "Input",
      description: "JSONL of audio samples (id, path or url, optional format/duration).",
      type: "path",
      group: "Workload",
      required: true,
      defaultValue: "test-data/asr.jsonl",
      omitWhenDefault: false,
    },
    {
      key: "groundTruth",
      flag: "ground-truth",
      label: "Ground truth",
      description: "JSONL with matching id and transcript for WER/CER.",
      type: "path",
      group: "Workload",
    },
    {
      key: "responseFormat",
      flag: "response-format",
      label: "Response format",
      type: "select",
      group: "Workload",
      defaultValue: "verbose-json",
      omitWhenDefault: true,
      options: [
        { value: "verbose-json", label: "verbose-json" },
        { value: "json", label: "json" },
        { value: "text", label: "text" },
        { value: "srt", label: "srt" },
        { value: "vtt", label: "vtt" },
      ],
    },
    {
      key: "language",
      flag: "language",
      label: "Language",
      type: "string",
      group: "Workload",
      defaultValue: "en",
      omitWhenDefault: true,
    },
    {
      key: "normalizer",
      flag: "normalizer",
      label: "Normalizer",
      type: "select",
      group: "Workload",
      defaultValue: "whisper-english",
      omitWhenDefault: true,
      options: [
        { value: "whisper-english", label: "whisper-english" },
        { value: "whisper-basic", label: "whisper-basic" },
        { value: "none", label: "none" },
      ],
    },
    {
      key: "dataLog",
      flag: "data-log",
      label: "Data log",
      type: "path",
      group: "Output",
      required: true,
      defaultValue: "results.jsonl",
      omitWhenDefault: true,
    },
    ...sharedEndpointFields({ requestTimeoutDefault: 120 }),
    ...sharedLoadFields({
      concurrencyDefault: 10,
      numRequestsRequired: false,
    }),
    ...sharedPublishFields(),
    ...sharedAdvancedFields({ logLevelDefault: "info" }),
  ],
};
