import type { CommandDef } from "../types";

export const imagegenCommand: CommandDef = {
  id: "imagegen",
  title: "Imagegen",
  description: "Image generation latency and artifact hashes.",
  href: "/imagegen",
  binary: "metrum-ai-bench-cli",
  subcommand: ["imagegen"],
  useDoubleDash: true,
  supportsRuns: true,
  fields: [
    {
      key: "scenario",
      flag: "scenario",
      label: "Scenario",
      type: "string",
      group: "Workload",
      required: true,
      defaultValue: "img",
      omitWhenDefault: false,
    },
    {
      key: "model",
      flag: "model",
      label: "Model",
      type: "string",
      group: "Workload",
      required: true,
      defaultValue: "dummy",
      omitWhenDefault: false,
    },
    {
      key: "prompt",
      flag: "prompt",
      label: "Prompt",
      description: "Single prompt. Alternative to Prompts file.",
      type: "textarea",
      group: "Workload",
      exclusiveWith: ["prompts"],
      placeholder: "a square",
    },
    {
      key: "prompts",
      flag: "prompts",
      label: "Prompts file",
      description: "JSONL prompts. Alternative to single Prompt.",
      type: "path",
      group: "Workload",
      exclusiveWith: ["prompt"],
    },
    {
      key: "promptField",
      flag: "prompt-field",
      label: "Prompt field",
      type: "string",
      group: "Workload",
      defaultValue: "prompt",
      omitWhenDefault: true,
    },
    {
      key: "idField",
      flag: "id-field",
      label: "ID field",
      type: "string",
      group: "Workload",
      defaultValue: "id",
      omitWhenDefault: true,
    },
    {
      key: "shufflePrompts",
      flag: "shuffle-prompts",
      label: "Shuffle prompts",
      type: "boolean",
      group: "Workload",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "negativePrompt",
      flag: "negative-prompt",
      label: "Negative prompt",
      type: "string",
      group: "Workload",
    },
    {
      key: "size",
      flag: "size",
      label: "Size",
      type: "string",
      group: "Workload",
      defaultValue: "1024x1024",
      omitWhenDefault: true,
    },
    {
      key: "n",
      flag: "n",
      label: "Images per request (n)",
      type: "number",
      group: "Workload",
      defaultValue: 1,
      omitWhenDefault: true,
      min: 1,
    },
    {
      key: "responseFormat",
      flag: "response-format",
      label: "Response format",
      type: "select",
      group: "Workload",
      defaultValue: "b64_json",
      omitWhenDefault: true,
      options: [
        { value: "b64_json", label: "b64_json" },
        { value: "url", label: "url" },
      ],
    },
    {
      key: "seed",
      flag: "seed",
      label: "Seed",
      type: "number",
      group: "Load",
      defaultValue: 0,
      omitWhenDefault: true,
    },
    {
      key: "seedMode",
      flag: "seed-mode",
      label: "Seed mode",
      type: "select",
      group: "Load",
      defaultValue: "increment",
      omitWhenDefault: true,
      options: [
        { value: "fixed", label: "fixed" },
        { value: "increment", label: "increment" },
        { value: "prompt", label: "prompt" },
      ],
    },
    {
      key: "numInferenceSteps",
      flag: "num-inference-steps",
      label: "Inference steps",
      type: "number",
      group: "Workload",
      min: 1,
    },
    {
      key: "guidanceScale",
      flag: "guidance-scale",
      label: "Guidance scale",
      type: "number",
      group: "Workload",
      step: 0.1,
    },
    {
      key: "trueCfgScale",
      flag: "true-cfg-scale",
      label: "True CFG scale",
      type: "number",
      group: "Workload",
      step: 0.1,
    },
    {
      key: "numRequests",
      flag: "num-requests",
      label: "Num requests",
      type: "number",
      group: "Load",
      required: true,
      defaultValue: 2,
      omitWhenDefault: false,
      min: 1,
    },
    {
      key: "concurrency",
      flag: "concurrency",
      label: "Concurrency",
      type: "number",
      group: "Load",
      required: true,
      defaultValue: 1,
      omitWhenDefault: false,
      min: 1,
    },
    {
      key: "warmupRequests",
      flag: "warmup-requests",
      label: "Warmup requests",
      type: "number",
      group: "Load",
      defaultValue: 0,
      omitWhenDefault: true,
      min: 0,
    },
    {
      key: "requestRate",
      flag: "request-rate",
      label: "Request rate (req/s)",
      type: "number",
      group: "Load",
      min: 0,
    },
    {
      key: "arrival",
      flag: "arrival",
      label: "Arrival",
      type: "select",
      group: "Load",
      defaultValue: "constant",
      omitWhenDefault: true,
      options: [
        { value: "constant", label: "constant" },
        { value: "poisson", label: "poisson" },
      ],
    },
    {
      key: "maxConcurrency",
      flag: "max-concurrency",
      label: "Max concurrency",
      type: "number",
      group: "Load",
      min: 1,
    },
    {
      key: "runs",
      flag: "runs",
      label: "Runs",
      type: "number",
      group: "Load",
      defaultValue: 1,
      omitWhenDefault: true,
      min: 1,
    },
    {
      key: "url",
      flag: "url",
      label: "URL",
      description: "OpenAI-compatible base URL, usually ending in /v1.",
      type: "url",
      group: "Endpoint",
      required: true,
      exclusiveWith: ["endpointsFile"],
      placeholder: "http://127.0.0.1:18321/v1",
      defaultValue: "http://127.0.0.1:18321/v1",
      omitWhenDefault: false,
    },
    {
      key: "apiKey",
      flag: "api-key",
      label: "API key",
      type: "password",
      group: "Endpoint",
      required: true,
      exclusiveWith: ["endpointsFile"],
      defaultValue: "dummy",
      omitWhenDefault: false,
    },
    {
      key: "endpoint",
      flag: "endpoint",
      label: "Endpoints",
      description: "Repeatable endpoint URLs for multi-endpoint mode.",
      type: "string-list",
      group: "Endpoint",
      defaultValue: [],
    },
    {
      key: "endpointsFile",
      flag: "endpoints-file",
      label: "Endpoints file",
      type: "path",
      group: "Endpoint",
      exclusiveWith: ["url", "apiKey"],
    },
    {
      key: "loadBalancer",
      flag: "load-balancer",
      label: "Load balancer",
      type: "select",
      group: "Endpoint",
      defaultValue: "round-robin",
      omitWhenDefault: true,
      options: [
        { value: "round-robin", label: "round-robin" },
        { value: "least-inflight", label: "least-inflight" },
        { value: "random", label: "random" },
        { value: "weighted-round-robin", label: "weighted-round-robin" },
      ],
    },
    {
      key: "endpointHealthCheck",
      flag: "endpoint-health-check",
      label: "Endpoint health check",
      type: "boolean",
      group: "Endpoint",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "healthPath",
      flag: "health-path",
      label: "Health path",
      type: "string",
      group: "Endpoint",
      defaultValue: "/models",
      omitWhenDefault: true,
    },
    {
      key: "maxEndpointFailures",
      flag: "max-endpoint-failures",
      label: "Max endpoint failures",
      type: "number",
      group: "Endpoint",
      defaultValue: 2,
      omitWhenDefault: true,
      min: 0,
    },
    {
      key: "endpointRetryAttempts",
      flag: "endpoint-retry-attempts",
      label: "Endpoint retry attempts",
      type: "number",
      group: "Endpoint",
      defaultValue: 0,
      omitWhenDefault: true,
      min: 0,
    },
    {
      key: "endpointRetryBackoffMs",
      flag: "endpoint-retry-backoff-ms",
      label: "Endpoint retry backoff (ms)",
      type: "number",
      group: "Endpoint",
      defaultValue: 100,
      omitWhenDefault: true,
      min: 0,
    },
    {
      key: "insecure",
      flag: "insecure",
      label: "Insecure TLS",
      type: "boolean",
      group: "Endpoint",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "caCert",
      flag: "ca-cert",
      label: "CA cert",
      type: "path",
      group: "Endpoint",
    },
    {
      key: "requestTimeout",
      flag: "request-timeout",
      label: "Request timeout (s)",
      type: "number",
      group: "Timeouts",
      defaultValue: 300,
      omitWhenDefault: true,
      min: 1,
    },
    {
      key: "connectTimeout",
      flag: "connect-timeout",
      label: "Connect timeout (s)",
      type: "number",
      group: "Timeouts",
      defaultValue: 30,
      omitWhenDefault: true,
      min: 1,
    },
    {
      key: "poolIdleTimeout",
      flag: "pool-idle-timeout",
      label: "Pool idle timeout (s)",
      type: "number",
      group: "Timeouts",
      defaultValue: 60,
      omitWhenDefault: true,
      min: 1,
    },
    {
      key: "tcpKeepalive",
      flag: "tcp-keepalive",
      label: "TCP keepalive (s)",
      type: "number",
      group: "Timeouts",
      defaultValue: 60,
      omitWhenDefault: true,
      min: 1,
    },
    {
      key: "dataLog",
      flag: "data-log",
      label: "Data log",
      type: "path",
      group: "Output",
      required: true,
      defaultValue: "results.jsonl",
      omitWhenDefault: false,
    },
    {
      key: "summaryJson",
      flag: "summary-json",
      label: "Summary JSON",
      type: "path",
      group: "Output",
    },
    {
      key: "artifactDir",
      flag: "artifact-dir",
      label: "Artifact dir",
      type: "path",
      group: "Output",
      defaultValue: "metrum-ai-bench-cli-imagegen-artifacts",
      omitWhenDefault: true,
    },
    {
      key: "saveResponseJson",
      flag: "save-response-json",
      label: "Save response JSON",
      type: "boolean",
      group: "Output",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "noSaveImages",
      flag: "no-save-images",
      label: "No save images",
      type: "boolean",
      group: "Output",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "overwriteArtifacts",
      flag: "overwrite-artifacts",
      label: "Overwrite artifacts",
      type: "boolean",
      group: "Output",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "debugLog",
      flag: "debug-log",
      label: "Debug log",
      type: "path",
      group: "Advanced",
      defaultValue: "debug.log",
      omitWhenDefault: true,
    },
    {
      key: "errorLog",
      flag: "error-log",
      label: "Error log",
      type: "path",
      group: "Advanced",
      defaultValue: "error.log",
      omitWhenDefault: true,
    },
    {
      key: "extraBodyJson",
      flag: "extra-body-json",
      label: "Extra body JSON",
      type: "json",
      group: "Advanced",
    },
    {
      key: "extraBodyFile",
      flag: "extra-body-file",
      label: "Extra body file",
      type: "path",
      group: "Advanced",
    },
    {
      key: "failOnError",
      flag: "fail-on-error",
      label: "Fail on error",
      type: "boolean",
      group: "Advanced",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "pricePerHour",
      flag: "price-per-hour",
      label: "Price per hour ($)",
      type: "number",
      group: "Publish / SUT",
      min: 0,
      step: 0.01,
    },
    {
      key: "sut",
      flag: "sut",
      label: "SUT file",
      type: "path",
      group: "Publish / SUT",
    },
    {
      key: "requireSut",
      flag: "require-sut",
      label: "Require SUT",
      type: "boolean",
      group: "Publish / SUT",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "redactHostname",
      flag: "redact-hostname",
      label: "Redact hostname",
      type: "boolean",
      group: "Publish / SUT",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "ntpCheck",
      flag: "ntp-check",
      label: "NTP check",
      type: "boolean",
      group: "Advanced",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "quiet",
      flag: "quiet",
      label: "Quiet",
      type: "boolean",
      group: "Advanced",
      booleanFlag: true,
      defaultValue: false,
    },
  ],
};
