import type { CommandDef } from "../types";
import {
  sharedAdvancedFields,
  sharedEndpointFields,
  sharedLoadFields,
  sharedPublishFields,
} from "../shared-fields";

export const llmCommand: CommandDef = {
  id: "llm",
  title: "LLM",
  description: "Text chat/completions benchmark (TTFT, ITL/TPOT, throughput).",
  href: "/llm",
  binary: "metrum-ai-bench-cli",
  subcommand: ["llm"],
  useDoubleDash: true,
  supportsRuns: true,
  fields: [
    {
      key: "scenario",
      flag: "scenario",
      label: "Scenario",
      type: "string",
      group: "Workload",
      required: true,
      defaultValue: "quickstart",
      omitWhenDefault: false,
    },
    {
      key: "model",
      flag: "model",
      label: "Model",
      type: "string",
      group: "Workload",
      required: true,
      defaultValue: "dummy",
      omitWhenDefault: false,
    },
    {
      key: "prompts",
      flag: "prompts",
      label: "Prompts",
      description: "JSONL file path or http(s) URL.",
      type: "path",
      group: "Workload",
      required: true,
      defaultValue: "test-data/llm-hi.jsonl",
      omitWhenDefault: false,
    },
    {
      key: "mode",
      flag: "mode",
      label: "Mode",
      type: "select",
      group: "Workload",
      required: true,
      defaultValue: "chat",
      omitWhenDefault: false,
      options: [
        { value: "chat", label: "chat" },
        { value: "completion", label: "completion" },
      ],
    },
    {
      key: "streaming",
      flag: "streaming",
      label: "Streaming",
      type: "boolean",
      group: "Workload",
      booleanFlag: true,
      defaultValue: true,
      omitWhenDefault: false,
    },
    {
      key: "maxTokens",
      flag: "max-tokens",
      label: "Max tokens",
      type: "number",
      group: "Workload",
      required: true,
      defaultValue: 64,
      omitWhenDefault: false,
      min: 1,
    },
    {
      key: "temperature",
      flag: "temperature",
      label: "Temperature",
      type: "number",
      group: "Workload",
      defaultValue: 0.1,
      omitWhenDefault: true,
      step: 0.1,
      min: 0,
    },
    {
      key: "dataLog",
      flag: "data-log",
      label: "Data log",
      type: "path",
      group: "Output",
      required: true,
      defaultValue: "results.jsonl",
      omitWhenDefault: false,
    },
    ...sharedEndpointFields({ requestTimeoutDefault: 300 }),
    ...sharedLoadFields(),
    ...sharedPublishFields(),
    ...sharedAdvancedFields({ logLevelDefault: "warn" }),
  ],
};
