import type { CommandDef } from "../types";

export const promptsCommand: CommandDef = {
  id: "prompts",
  title: "Prompts",
  description: "Select an ISL/OSL mix from metrum-ai/prompt-library.",
  href: "/prompts",
  binary: "metrum-ai-bench-cli",
  subcommand: ["prompts"],
  useDoubleDash: false,
  supportsRuns: false,
  fields: [
    {
      key: "dataset",
      flag: "dataset",
      label: "Dataset",
      type: "string",
      group: "Workload",
      defaultValue: "metrum-ai/prompt-library",
      omitWhenDefault: true,
    },
    {
      key: "revision",
      flag: "revision",
      label: "Revision",
      description: "Hub revision (default main). Pass a 40-char SHA to pin.",
      type: "string",
      group: "Workload",
      defaultValue: "main",
      omitWhenDefault: true,
    },
    {
      key: "config",
      flag: "config",
      label: "Config",
      type: "select",
      group: "Workload",
      defaultValue: "sample",
      omitWhenDefault: true,
      options: [
        { value: "sample", label: "sample" },
        { value: "full", label: "full" },
      ],
    },
    {
      key: "split",
      flag: "split",
      label: "Split",
      type: "string",
      group: "Workload",
      defaultValue: "train",
      omitWhenDefault: true,
    },
    {
      key: "requirePinnedRevision",
      flag: "require-pinned-revision",
      label: "Require pinned revision",
      type: "boolean",
      group: "Workload",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "allowMovingRevision",
      flag: "allow-moving-revision",
      label: "Allow moving revision (deprecated no-op)",
      type: "boolean",
      group: "Workload",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "cacheDir",
      flag: "cache-dir",
      label: "Cache dir",
      type: "path",
      group: "Workload",
    },
    {
      key: "offline",
      flag: "offline",
      label: "Offline",
      type: "boolean",
      group: "Workload",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "localParquet",
      flag: "local-parquet",
      label: "Local parquet",
      description: "Repeatable local parquet shards (skips Hub).",
      type: "path-list",
      group: "Workload",
      defaultValue: [],
    },
    {
      key: "localJsonl",
      flag: "local-jsonl",
      label: "Local JSONL",
      type: "path",
      group: "Workload",
    },
    {
      key: "count",
      flag: "count",
      label: "Count",
      description: "Preferred mix size (soft target).",
      type: "number",
      group: "Load",
      min: 1,
      defaultValue: 64,
      omitWhenDefault: false,
    },
    {
      key: "countSlack",
      flag: "count-slack",
      label: "Count slack",
      type: "number",
      group: "Load",
      min: 0,
    },
    {
      key: "seed",
      flag: "seed",
      label: "Seed",
      type: "number",
      group: "Load",
      defaultValue: 0,
      omitWhenDefault: true,
    },
    {
      key: "profile",
      flag: "profile",
      label: "Profile",
      description: "Named ISL/OSL profile. Conflicts with explicit targets.",
      type: "select",
      group: "Workload",
      exclusiveWith: ["islTarget", "oslTarget"],
      options: [
        { value: "", label: "(none)" },
        { value: "chat-short", label: "chat-short" },
        { value: "chat-medium", label: "chat-medium" },
        { value: "rag-medium", label: "rag-medium" },
        { value: "summarize-long", label: "summarize-long" },
        { value: "code-medium", label: "code-medium" },
      ],
      defaultValue: "",
      omitWhenDefault: true,
    },
    {
      key: "islTarget",
      flag: "isl-target",
      label: "ISL target",
      type: "number",
      group: "Workload",
      exclusiveWith: ["profile"],
      min: 0,
      defaultValue: 512,
      omitWhenDefault: false,
    },
    {
      key: "islUnit",
      flag: "isl-unit",
      label: "ISL unit",
      type: "select",
      group: "Workload",
      defaultValue: "tokens",
      omitWhenDefault: true,
      options: [
        { value: "tokens", label: "tokens" },
        { value: "words", label: "words" },
      ],
    },
    {
      key: "islStat",
      flag: "isl-stat",
      label: "ISL stat",
      type: "select",
      group: "Workload",
      defaultValue: "median",
      omitWhenDefault: true,
      options: [
        { value: "median", label: "median" },
        { value: "mean", label: "mean" },
      ],
    },
    {
      key: "islTolerance",
      flag: "isl-tolerance",
      label: "ISL tolerance",
      type: "number",
      group: "Workload",
      defaultValue: 64,
      omitWhenDefault: false,
      min: 0,
    },
    {
      key: "oslTarget",
      flag: "osl-target",
      label: "OSL target",
      type: "number",
      group: "Workload",
      exclusiveWith: ["profile"],
      min: 0,
      defaultValue: 128,
      omitWhenDefault: false,
    },
    {
      key: "oslUnit",
      flag: "osl-unit",
      label: "OSL unit",
      type: "select",
      group: "Workload",
      defaultValue: "tokens",
      omitWhenDefault: true,
      options: [
        { value: "tokens", label: "tokens" },
        { value: "words", label: "words" },
      ],
    },
    {
      key: "oslStat",
      flag: "osl-stat",
      label: "OSL stat",
      type: "select",
      group: "Workload",
      defaultValue: "median",
      omitWhenDefault: true,
      options: [
        { value: "median", label: "median" },
        { value: "mean", label: "mean" },
      ],
    },
    {
      key: "oslTolerance",
      flag: "osl-tolerance",
      label: "OSL tolerance",
      type: "number",
      group: "Workload",
      defaultValue: 32,
      omitWhenDefault: false,
      min: 0,
    },
    {
      key: "islTokenBasis",
      flag: "isl-token-basis",
      label: "ISL token basis",
      type: "select",
      group: "Advanced",
      defaultValue: "supplied-target",
      omitWhenDefault: true,
      options: [{ value: "supplied-target", label: "supplied-target" }],
    },
    {
      key: "reasoning",
      flag: "reasoning",
      label: "Reasoning",
      type: "select",
      group: "Workload",
      defaultValue: "any",
      omitWhenDefault: true,
      options: [
        { value: "any", label: "any" },
        { value: "true", label: "true" },
        { value: "false", label: "false" },
      ],
    },
    {
      key: "maxRepeats",
      flag: "max-repeats",
      label: "Max repeats",
      type: "number",
      group: "Advanced",
      defaultValue: 8,
      omitWhenDefault: true,
      min: 1,
    },
    {
      key: "noRepeats",
      flag: "no-repeats",
      label: "No repeats",
      type: "boolean",
      group: "Advanced",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "oslTokensPerWord",
      flag: "osl-tokens-per-word",
      label: "OSL tokens per word",
      type: "number",
      group: "Advanced",
      min: 0,
      step: 0.1,
    },
    {
      key: "selectWorkLimit",
      flag: "select-work-limit",
      label: "Select work limit",
      type: "number",
      group: "Advanced",
      defaultValue: 50000,
      omitWhenDefault: true,
      min: 1,
    },
    {
      key: "output",
      flag: "output",
      label: "Output JSONL",
      type: "path",
      group: "Output",
      required: true,
      defaultValue: "/tmp/mix.jsonl",
      omitWhenDefault: false,
    },
    {
      key: "report",
      flag: "report",
      label: "Report JSON",
      type: "path",
      group: "Output",
      defaultValue: "/tmp/mix-report.json",
      omitWhenDefault: false,
    },
    {
      key: "quiet",
      flag: "quiet",
      label: "Quiet",
      type: "boolean",
      group: "Advanced",
      booleanFlag: true,
      defaultValue: false,
    },
  ],
};
