import type { CommandDef } from "../types";

export const strategicCommand: CommandDef = {
  id: "strategic",
  title: "Strategic",
  description:
    "Concurrency/rate sweeps, knee detection, sessions, and exports (separate binary).",
  href: "/strategic",
  binary: "metrum-ai-bench-cli-strategic",
  subcommand: [],
  useDoubleDash: false,
  supportsRuns: false,
  fields: [
    {
      key: "url",
      flag: "url",
      label: "URL",
      type: "url",
      group: "Endpoint",
      required: true,
      placeholder: "http://127.0.0.1:18321/v1/chat/completions",
    },
    {
      key: "apiKey",
      flag: "api-key",
      label: "API key",
      type: "password",
      group: "Endpoint",
      defaultValue: "",
      omitWhenDefault: true,
      placeholder: "dummy",
    },
    {
      key: "model",
      flag: "model",
      label: "Model",
      type: "string",
      group: "Workload",
      required: true,
      defaultValue: "dummy",
      omitWhenDefault: false,
    },
    {
      key: "kind",
      flag: "kind",
      label: "Kind",
      type: "select",
      group: "Workload",
      defaultValue: "chat",
      omitWhenDefault: true,
      options: [
        { value: "chat", label: "chat" },
        { value: "embeddings", label: "embeddings" },
        { value: "rerank", label: "rerank" },
      ],
    },
    {
      key: "streaming",
      flag: "streaming",
      label: "Streaming",
      type: "boolean",
      group: "Workload",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "requestsPerStage",
      flag: "requests-per-stage",
      label: "Requests per stage",
      type: "number",
      group: "Load",
      defaultValue: 100,
      omitWhenDefault: true,
      min: 1,
    },
    {
      key: "sweep",
      flag: "sweep",
      label: "Sweep",
      type: "string",
      group: "Load",
      defaultValue: "1,2,4,8",
      omitWhenDefault: true,
    },
    {
      key: "sweepBy",
      flag: "sweep-by",
      label: "Sweep by",
      type: "select",
      group: "Load",
      defaultValue: "concurrency",
      omitWhenDefault: true,
      options: [
        { value: "concurrency", label: "concurrency" },
        { value: "rate", label: "rate" },
      ],
    },
    {
      key: "maxInFlight",
      flag: "max-in-flight",
      label: "Max in flight",
      type: "number",
      group: "Load",
      defaultValue: 256,
      omitWhenDefault: true,
      min: 1,
    },
    {
      key: "prompt",
      flag: "prompt",
      label: "Prompt",
      type: "textarea",
      group: "Workload",
      defaultValue: "Hello",
      omitWhenDefault: true,
    },
    {
      key: "prompts",
      flag: "prompts",
      label: "Prompts file",
      type: "path",
      group: "Workload",
    },
    {
      key: "maxTokens",
      flag: "max-tokens",
      label: "Max tokens",
      type: "number",
      group: "Workload",
      min: 1,
    },
    {
      key: "ignoreEos",
      flag: "ignore-eos",
      label: "Ignore EOS",
      type: "boolean",
      group: "Workload",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "minTokens",
      flag: "min-tokens",
      label: "Min tokens",
      type: "number",
      group: "Workload",
      min: 0,
    },
    {
      key: "extraBodyJson",
      flag: "extra-body-json",
      label: "Extra body JSON",
      type: "json",
      group: "Advanced",
    },
    {
      key: "warmupRequests",
      flag: "warmup-requests",
      label: "Warmup requests",
      type: "number",
      group: "Load",
      defaultValue: 0,
      omitWhenDefault: true,
      min: 0,
    },
    {
      key: "seed",
      flag: "seed",
      label: "Seed",
      type: "number",
      group: "Load",
      defaultValue: 0,
      omitWhenDefault: true,
    },
    {
      key: "shufflePrompts",
      flag: "shuffle-prompts",
      label: "Shuffle prompts",
      type: "boolean",
      group: "Workload",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "sessions",
      flag: "sessions",
      label: "Sessions file",
      type: "path",
      group: "Workload",
    },
    {
      key: "prefixControl",
      flag: "prefix-control",
      label: "Prefix control",
      type: "select",
      group: "Workload",
      defaultValue: "shared",
      omitWhenDefault: true,
      options: [
        { value: "shared", label: "shared" },
        { value: "unique", label: "unique" },
        { value: "none", label: "none" },
      ],
    },
    {
      key: "sharedPrefix",
      flag: "shared-prefix",
      label: "Shared prefix",
      type: "string",
      group: "Workload",
    },
    {
      key: "jsonSchema",
      flag: "json-schema",
      label: "JSON schema",
      type: "path",
      group: "Advanced",
    },
    {
      key: "tools",
      flag: "tools",
      label: "Tools",
      type: "path",
      group: "Advanced",
    },
    {
      key: "metricsUrl",
      flag: "metrics-url",
      label: "Metrics URL",
      type: "url",
      group: "Advanced",
    },
    {
      key: "metricsIntervalMs",
      flag: "metrics-interval-ms",
      label: "Metrics interval (ms)",
      type: "number",
      group: "Advanced",
      defaultValue: 250,
      omitWhenDefault: true,
      min: 1,
    },
    {
      key: "ndjson",
      flag: "ndjson",
      label: "NDJSON log",
      type: "path",
      group: "Output",
    },
    {
      key: "telemetry",
      flag: "telemetry",
      label: "Telemetry YAML",
      type: "path",
      group: "Advanced",
    },
    {
      key: "requireTelemetry",
      flag: "require-telemetry",
      label: "Require telemetry",
      type: "boolean",
      group: "Advanced",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "requireTelemetryFailures",
      flag: "require-telemetry-failures",
      label: "Require telemetry failures",
      type: "number",
      group: "Advanced",
      defaultValue: 3,
      omitWhenDefault: true,
      min: 1,
    },
    {
      key: "html",
      flag: "html",
      label: "HTML report",
      type: "path",
      group: "Output",
      defaultValue: "metrum-ai-bench-cli-report.html",
      omitWhenDefault: true,
    },
    {
      key: "csv",
      flag: "csv",
      label: "CSV export",
      type: "path",
      group: "Output",
      defaultValue: "metrum-ai-bench-cli-requests.csv",
      omitWhenDefault: true,
    },
    {
      key: "mlperfDir",
      flag: "mlperf-dir",
      label: "MLPerf dir",
      type: "path",
      group: "Output",
    },
    {
      key: "mlperfScenario",
      flag: "mlperf-scenario",
      label: "MLPerf scenario",
      type: "select",
      group: "Output",
      defaultValue: "server",
      omitWhenDefault: true,
      options: [
        { value: "server", label: "server" },
        { value: "offline", label: "offline" },
      ],
    },
    {
      key: "otlpEndpoint",
      flag: "otlp-endpoint",
      label: "OTLP endpoint",
      type: "url",
      group: "Advanced",
    },
    {
      key: "otlpServiceName",
      flag: "otlp-service-name",
      label: "OTLP service name",
      type: "string",
      group: "Advanced",
      defaultValue: "metrum-ai-bench-cli",
      omitWhenDefault: true,
    },
    {
      key: "timeoutSeconds",
      flag: "timeout-seconds",
      label: "Timeout (s)",
      type: "number",
      group: "Timeouts",
      defaultValue: 300,
      omitWhenDefault: true,
      min: 1,
    },
    {
      key: "slo",
      flag: "slo",
      label: "SLO thresholds",
      type: "slo-list",
      group: "Advanced",
      defaultValue: [],
    },
    {
      key: "pricePerHour",
      flag: "price-per-hour",
      label: "Price per hour ($)",
      type: "number",
      group: "Publish / SUT",
      min: 0,
      step: 0.01,
    },
    {
      key: "islTarget",
      flag: "isl-target",
      label: "ISL target",
      type: "number",
      group: "Publish / SUT",
      min: 0,
    },
    {
      key: "oslTarget",
      flag: "osl-target",
      label: "OSL target",
      type: "number",
      group: "Publish / SUT",
      min: 0,
    },
    {
      key: "islTolerance",
      flag: "isl-tolerance",
      label: "ISL tolerance",
      type: "number",
      group: "Publish / SUT",
      defaultValue: 0,
      omitWhenDefault: true,
      min: 0,
    },
    {
      key: "oslTolerance",
      flag: "osl-tolerance",
      label: "OSL tolerance",
      type: "number",
      group: "Publish / SUT",
      defaultValue: 0,
      omitWhenDefault: true,
      min: 0,
    },
    {
      key: "promptMixReport",
      flag: "prompt-mix-report",
      label: "Prompt mix report",
      type: "path",
      group: "Publish / SUT",
    },
    {
      key: "failOnOslMismatch",
      flag: "fail-on-osl-mismatch",
      label: "Fail on OSL mismatch",
      type: "boolean",
      group: "Publish / SUT",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "sut",
      flag: "sut",
      label: "SUT file",
      type: "path",
      group: "Publish / SUT",
    },
    {
      key: "requireSut",
      flag: "require-sut",
      label: "Require SUT",
      type: "boolean",
      group: "Publish / SUT",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "redactHostname",
      flag: "redact-hostname",
      label: "Redact hostname",
      type: "boolean",
      group: "Publish / SUT",
      booleanFlag: true,
      defaultValue: false,
    },
  ],
};
