import type { CommandDef } from "../types";

export const preflightCommand: CommandDef = {
  id: "preflight",
  title: "Preflight",
  description: "Probe an OpenAI-compatible serving endpoint before a long run.",
  href: "/preflight",
  binary: "metrum-ai-bench-cli",
  subcommand: ["preflight"],
  useDoubleDash: false,
  supportsRuns: false,
  fields: [
    {
      key: "url",
      flag: "url",
      label: "URL",
      type: "url",
      group: "Endpoint",
      required: true,
      placeholder: "http://127.0.0.1:18321/v1/chat/completions",
      defaultValue: "http://127.0.0.1:18321/v1/chat/completions",
      omitWhenDefault: false,
    },
    {
      key: "apiKey",
      flag: "api-key",
      label: "API key",
      type: "password",
      group: "Endpoint",
      required: true,
      defaultValue: "dummy",
      omitWhenDefault: false,
    },
    {
      key: "model",
      flag: "model",
      label: "Model",
      type: "string",
      group: "Workload",
      defaultValue: "dummy",
      omitWhenDefault: true,
    },
    {
      key: "connectTimeout",
      flag: "connect-timeout",
      label: "Connect timeout (s)",
      type: "number",
      group: "Timeouts",
      defaultValue: 10,
      omitWhenDefault: true,
      min: 1,
    },
    {
      key: "requestTimeout",
      flag: "request-timeout",
      label: "Request timeout (s)",
      type: "number",
      group: "Timeouts",
      defaultValue: 60,
      omitWhenDefault: true,
      min: 1,
    },
    {
      key: "latencySamples",
      flag: "latency-samples",
      label: "Latency samples",
      type: "number",
      group: "Load",
      defaultValue: 3,
      omitWhenDefault: true,
      min: 1,
    },
    {
      key: "json",
      flag: "json",
      label: "JSON report",
      type: "boolean",
      group: "Output",
      booleanFlag: true,
      defaultValue: false,
    },
  ],
};

export const sutInitCommand: CommandDef = {
  id: "sut-init",
  title: "SUT init",
  description: "Write a SUT JSON template (optionally probe local host facts).",
  href: "/sut",
  binary: "metrum-ai-bench-cli",
  subcommand: ["sut", "init"],
  useDoubleDash: false,
  supportsRuns: false,
  fields: [
    {
      key: "output",
      flag: "output",
      label: "Output",
      type: "path",
      group: "Output",
      defaultValue: "sut.json",
      omitWhenDefault: true,
    },
    {
      key: "probe",
      flag: "probe",
      label: "Probe local host",
      description: "Probe local nvidia-smi / OS / CPU / memory (never remote SSH).",
      type: "boolean",
      group: "General",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "force",
      flag: "force",
      label: "Force overwrite",
      type: "boolean",
      group: "General",
      booleanFlag: true,
      defaultValue: false,
    },
  ],
};

export const compareCommand: CommandDef = {
  id: "compare",
  title: "Compare",
  description: "Compare two or more strategic sweep summaries or request CSVs.",
  href: "/compare",
  binary: "metrum-ai-bench-cli",
  subcommand: ["compare"],
  useDoubleDash: false,
  supportsRuns: false,
  fields: [
    {
      key: "inputs",
      flag: "",
      label: "Inputs",
      description: "Two or more strategic stdout JSON files and/or request CSVs.",
      type: "path-list",
      group: "Workload",
      required: true,
      positional: true,
      defaultValue: [],
    },
    {
      key: "labels",
      flag: "labels",
      label: "Labels",
      description: "Comma-separated labels matching input order.",
      type: "string",
      group: "Workload",
      joinWith: ",",
    },
    {
      key: "format",
      flag: "format",
      label: "Format",
      type: "select",
      group: "Output",
      defaultValue: "markdown",
      omitWhenDefault: true,
      options: [
        { value: "markdown", label: "markdown" },
        { value: "json", label: "json" },
      ],
    },
    {
      key: "output",
      flag: "output",
      label: "Output path",
      type: "path",
      group: "Output",
    },
  ],
};

export const selftestCommand: CommandDef = {
  id: "selftest",
  title: "Selftest",
  description: "Print client environment JSON and selftest: ok.",
  href: "/selftest",
  binary: "metrum-ai-bench-cli",
  subcommand: ["selftest"],
  useDoubleDash: false,
  supportsRuns: false,
  fields: [],
};

export const mockServerCommand: CommandDef = {
  id: "mock-server",
  title: "Mock server",
  description: "Deterministic OpenAI-compatible mock for strategic fixtures.",
  href: "/mock-server",
  binary: "metrum-ai-bench-cli-mock-server",
  subcommand: [],
  useDoubleDash: false,
  supportsRuns: false,
  fields: [
    {
      key: "listen",
      flag: "listen",
      label: "Listen",
      type: "string",
      group: "Endpoint",
      defaultValue: "127.0.0.1:8080",
      omitWhenDefault: true,
    },
    {
      key: "latencyMs",
      flag: "latency-ms",
      label: "Latency (ms)",
      type: "number",
      group: "Load",
      defaultValue: 0,
      omitWhenDefault: true,
      min: 0,
    },
    {
      key: "failEvery",
      flag: "fail-every",
      label: "Fail every N",
      type: "number",
      group: "Load",
      defaultValue: 0,
      omitWhenDefault: true,
      min: 0,
    },
    {
      key: "telemetryFixture",
      flag: "telemetry-fixture",
      label: "Telemetry fixture",
      type: "boolean",
      group: "Advanced",
      booleanFlag: true,
      defaultValue: false,
    },
  ],
};
