import type { CommandDef } from "../types";
import {
  sharedAdvancedFields,
  sharedEndpointFields,
  sharedLoadFields,
  sharedPublishFields,
} from "../shared-fields";

export const vlmCommand: CommandDef = {
  id: "vlm",
  title: "VLM",
  description: "Vision-language chat benchmark with image payloads.",
  href: "/vlm",
  binary: "metrum-ai-bench-cli",
  subcommand: ["vlm"],
  useDoubleDash: true,
  supportsRuns: true,
  fields: [
    {
      key: "scenario",
      flag: "scenario",
      label: "Scenario",
      type: "string",
      group: "Workload",
      required: true,
      defaultValue: "vlm",
      omitWhenDefault: false,
    },
    {
      key: "model",
      flag: "model",
      label: "Model",
      type: "string",
      group: "Workload",
      required: true,
      defaultValue: "dummy",
      omitWhenDefault: false,
    },
    {
      key: "prompts",
      flag: "prompts",
      label: "Prompts",
      description: 'JSONL with "prompt" and "image_url" / "image_urls".',
      type: "path",
      group: "Workload",
      required: true,
      defaultValue: "test-data/vlm.jsonl",
      omitWhenDefault: false,
    },
    {
      key: "streaming",
      flag: "streaming",
      label: "Streaming",
      type: "boolean",
      group: "Workload",
      booleanFlag: true,
      defaultValue: true,
      omitWhenDefault: false,
    },
    {
      key: "maxTokens",
      flag: "max-tokens",
      label: "Max tokens",
      type: "number",
      group: "Workload",
      required: true,
      defaultValue: 16,
      omitWhenDefault: false,
      min: 1,
    },
    {
      key: "temperature",
      flag: "temperature",
      label: "Temperature",
      type: "number",
      group: "Workload",
      defaultValue: 0.1,
      omitWhenDefault: true,
      step: 0.1,
      min: 0,
    },
    {
      key: "numImagesBatch",
      flag: "num-images-batch",
      label: "Images per request",
      type: "number",
      group: "Workload",
      defaultValue: 1,
      omitWhenDefault: true,
      min: 1,
    },
    {
      key: "imageCacheSize",
      flag: "image-cache-size",
      label: "Image cache size",
      type: "number",
      group: "Workload",
      defaultValue: 1000,
      omitWhenDefault: true,
      min: 1,
    },
    {
      key: "maxImageDimension",
      flag: "max-image-dimension",
      label: "Max image dimension",
      type: "number",
      group: "Workload",
      min: 1,
    },
    {
      key: "reencodeJpeg",
      flag: "reencode-jpeg",
      label: "Re-encode JPEG",
      type: "boolean",
      group: "Workload",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "imageDetail",
      flag: "image-detail",
      label: "Image detail",
      type: "select",
      group: "Workload",
      defaultValue: "low",
      omitWhenDefault: true,
      options: [
        { value: "low", label: "low" },
        { value: "high", label: "high" },
      ],
    },
    {
      key: "serverSideDownload",
      flag: "server-side-download",
      label: "Server-side download",
      type: "boolean",
      group: "Workload",
      booleanFlag: true,
      defaultValue: false,
    },
    {
      key: "dataLog",
      flag: "data-log",
      label: "Data log",
      type: "path",
      group: "Output",
      required: true,
      defaultValue: "results.jsonl",
      omitWhenDefault: false,
    },
    ...sharedEndpointFields({ requestTimeoutDefault: 120 }),
    ...sharedLoadFields(),
    ...sharedPublishFields(),
    ...sharedAdvancedFields({ logLevelDefault: "warn" }),
  ],
};
